// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';
import {logger} from '../models';
import {filter} from '../models';

export function GetCacheInfo():Promise<Record<string, any>>;

export function GetConfig():Promise<config.Config>;

export function GetCtx():Promise<context.Context>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function GetStats():Promise<filter.Stats>;

export function IsProtectionEnabled():Promise<boolean>;

export function LookupBlockSource(arg1:string):Promise<Array<string>>;

export function MinimizeToTray():Promise<void>;

export function QuitApp():Promise<void>;

export function ResetAllowlist():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetProtectionEnabled(arg1:boolean):Promise<void>;

export function ToggleProtection():Promise<void>;

export function TriggerUpdate():Promise<void>;
