// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCtx() {
  return window['go']['main']['App']['GetCtx']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function IsProtectionEnabled() {
  return window['go']['main']['App']['IsProtectionEnabled']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetProtectionEnabled(arg1) {
  return window['go']['main']['App']['SetProtectionEnabled'](arg1);
}

export function ToggleProtection() {
  return window['go']['main']['App']['ToggleProtection']();
}

export function TriggerUpdate() {
  return window['go']['main']['App']['TriggerUpdate']();
}
